//
//  DogBreedListViewController.swift
//  doglist
//
//  Created by Hélio Mesquita on 25/05/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DogBreedsListDisplayLogic: class {
}

class DogBreedsListViewController: UIViewController {

  var interactor: DogBreedsListBusinessLogic?
  var router: (DogBreedsListRoutingLogic & DogBreedsListDataPassing)?

  private func setup() {
    let viewController = self
    let interactor = DogBreedsListInteractor()
    let presenter = DogBreedsListPresenter()
    let router = DogBreedsListRouter()
    viewController.interactor = interactor
    viewController.router = router
    presenter.viewController = viewController
    interactor.presenter = presenter
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  override func viewDidLoad() {
    super.viewDidLoad()
  }

}

extension DogBreedsListViewController: DogBreedsListDisplayLogic {

}
