//
//  LoginRouter.swift
//  doglist
//
//  Created by Hélio Mesquita on 24/05/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
  func routeToPhotoList()
}

protocol LoginDataPassing {
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: LoginRoutingLogic, LoginDataPassing {

  weak var viewController: LoginViewController?
  var dataStore: LoginDataStore?

  func routeToPhotoList() {
    guard let destinationVC = R.storyboard.main.photoList() else { return }
    var destinationDS = destinationVC.router!.dataStore!
    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    let nav = UINavigationController(rootViewController: destinationVC)
    viewController?.present(nav, animated: true, completion: nil)
  }
  
  func passDataToSomewhere(source: LoginDataStore, destination: inout DogPhotoListDataStore) {
    destination.session = source.session
  }
}
