//
//  LoginWorker.swift
//  doglist
//
//  Created by Hélio Mesquita on 24/05/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker {

  let serviceProvider: ServiceProvider<Login.Response>

  init(serviceProvider: ServiceProvider<Login.Response> = ServiceProvider<Login.Response>()) {
    self.serviceProvider = serviceProvider
  }

  func performLogin(email: String) {
    let emailEncodable = Login.BodyRequest(email: email)
    serviceProvider.execute(request: LoginProvider(emailEncodable: emailEncodable), onSuccess: { response in

    }, onError: { error in

    })
  }
  
}
