//
//  LoginModels.swift
//  doglist
//
//  Created by Hélio Mesquita on 24/05/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {

  struct BodyRequest: Encodable {
    var email: String
  }

  struct Response: Decodable {
  }

  struct ViewModel {
  }

}
