//
//  LoginWorker.swift
//  doglist
//
//  Created by Hélio Mesquita on 24/05/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import PromiseKit
import UIKit

class LoginWorker {

  let serviceProvider: ServiceProvider

  init(serviceProvider: ServiceProvider = ServiceProvider()) {
    self.serviceProvider = serviceProvider
  }

  func performLogin(validatedEmail: String) -> Promise<Login.Response> {
    let emailEncodable = Login.BodyRequest(email: validatedEmail)
    let requestProvider = LoginProvider(emailEncodable: emailEncodable)

    return serviceProvider.execute(request: requestProvider, parser: Login.Response.self)
  }
  
}
