//
//  LoginViewController.swift
//  doglist
//
//  Created by Hélio Mesquita on 24/05/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: class {
  func showInvalidEmailAlert(message: String)
  func showTitle(text: String)
  func showSubtitle(text: String)
  func showButtonTitle(text: String)
}

class LoginViewController: UIViewController {

  @IBOutlet weak var lblTitle: UILabel!
  @IBOutlet weak var lblSubtitle: UILabel!
  @IBOutlet weak var txfEmail: UITextField!
  @IBOutlet weak var bttOut: UIButton!

  var interactor: LoginBusinessLogic?
  var router: (LoginRoutingLogic & LoginDataPassing)?
  
  private func setup() {
    let viewController = self
    let interactor = LoginInteractor()
    let presenter = LoginPresenter()
    let router = LoginRouter()
    viewController.interactor = interactor
    viewController.router = router
    presenter.viewController = viewController
    interactor.presenter = presenter
    router.viewController = viewController
    router.dataStore = interactor
  }

  override func viewDidLoad() {
    super.viewDidLoad()
    bttOut.layer.cornerRadius = 24
    setup()
  }

  @IBAction func continueButton(_ sender: Any) {
    interactor?.validateEmail(txfEmail.text)
  }

}

extension LoginViewController: LoginDisplayLogic {

  func showButtonTitle(text: String) {
    bttOut.setTitle(text, for: .normal)
  }

  func showInvalidEmailAlert(message: String) {

  }

  func showTitle(text: String) {
    lblTitle.text = text
  }

  func showSubtitle(text: String) {
    lblSubtitle.text = text
  }

}
