//
//  LoginPresenter.swift
//  doglist
//
//  Created by Hélio Mesquita on 24/05/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
  func presentTitle()
  func presentSubtitle()
  func presentInvalidEmailAlert()
  func presentButtonTitle()
}

class LoginPresenter: LoginPresentationLogic {

  weak var viewController: LoginDisplayLogic?

  func presentInvalidEmailAlert() {
    viewController?.showInvalidEmailAlert(message: R.string.login.invalid_email())
  }

  func presentTitle() {
    viewController?.showTitle(text: R.string.login.welcome())
  }

  func presentSubtitle() {
    viewController?.showSubtitle(text: R.string.login.digit_your_email_to_continue())
  }

  func presentButtonTitle() {
    viewController?.showButtonTitle(text: R.string.login.continue())
  }
  
}
