//
//  DogPhotoListViewController.swift
//  doglist
//
//  Created by Hélio Mesquita on 25/05/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SDWebImage

protocol DogPhotoListDisplayLogic: class {
  func showAlert(message: String)
  func showTitle(_ text: String)
  func reloadCollection()
}

class DogPhotoListViewController: UIViewController {

  @IBOutlet weak var collectionView: UICollectionView!

  var interactor: DogPhotoListBusinessLogic?
  var router: (DogPhotoListRoutingLogic & DogPhotoListDataPassing)?

  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)   {
    super.init(nibName: R.storyboard.main.photoList.identifier, bundle: nibBundleOrNil)
    setup()
  }

  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  private func setup() {
    let viewController = self
    let interactor = DogPhotoListInteractor()
    let presenter = DogPhotoListPresenter()
    let router = DogPhotoListRouter()
    viewController.interactor = interactor
    viewController.router = router
    presenter.viewController = viewController
    interactor.presenter = presenter
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  override func viewDidLoad() {
    super.viewDidLoad()
    collectionView.delegate = self
    collectionView.dataSource = self
    configureFlowLayout()
  }

  func configureFlowLayout() {
    let flow = collectionView.collectionViewLayout as? UICollectionViewFlowLayout
    let itemSpacing: CGFloat = 3
    let itemsInOneLine: CGFloat = 3
    flow?.sectionInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
    let width = UIScreen.main.bounds.size.width - itemSpacing * CGFloat(itemsInOneLine - 1)
    flow?.itemSize = CGSize(width: floor(width/itemsInOneLine), height: width/itemsInOneLine)
    flow?.minimumInteritemSpacing = 3
    flow?.minimumLineSpacing = 3
  }

  override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    interactor?.load()
  }

  @IBAction func chooseBreed(_ sender: Any) {
    router?.routeToChooseBreed()
  }

}

extension DogPhotoListViewController: DogPhotoListDisplayLogic {

  func showTitle(_ text: String) {
    navigationItem.title = text
  }

  func reloadCollection() {
    collectionView.reloadData()
  }

  func showAlert(message: String) {
    let alertController = UIAlertController(title: nil, message: message, preferredStyle: .alert)
    let action = UIAlertAction(title: R.string.general.ok(), style: .cancel, handler: nil)
    alertController.addAction(action)
    let tryAgain = UIAlertAction(title: R.string.general.tryAgain(), style: .default) { _ in
      self.interactor?.load()
    }
    alertController.addAction(tryAgain)
    present(alertController, animated: true, completion: nil)
  }

}

extension DogPhotoListViewController: UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout{

  func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
    return interactor?.numberOfRows ?? 0
  }

  func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
    let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "photoCell", for: indexPath) as? DogCollectionViewCell
    let url = URL(string: interactor?.cellForRow(at: indexPath.row) ?? "")
    cell?.backgroundImageView.sd_setImage(with: url)
    return cell ?? UICollectionViewCell()
  }

}
