//
//  DogPhotoListRouter.swift
//  doglist
//
//  Created by Hélio Mesquita on 25/05/19.
//  Copyright (c) 2019 Hélio Mesquita. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DogPhotoListRoutingLogic {
  func routeToChooseBreed()
}

protocol DogPhotoListDataPassing {
  var dataStore: DogPhotoListDataStore? { get }
}

class DogPhotoListRouter: DogPhotoListRoutingLogic, DogPhotoListDataPassing {

  weak var viewController: DogPhotoListViewController?
  var dataStore: DogPhotoListDataStore?

  func routeToChooseBreed(){
    guard let destinationVC = R.storyboard.main.breedList() else { return }
    var destinationDS = destinationVC.router!.dataStore!
    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    viewController?.navigationController?.pushViewController(destinationVC, animated: true)
  }

  func passDataToSomewhere(source: DogPhotoListDataStore, destination: inout DogBreedsListDataStore) {
    destination.session = source.session
  }
  
}
