//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.login` struct is generated, and contains static references to 4 localization keys.
    struct login {
      /// Value: Bem vindo!
      static let welcome = Rswift.StringResource(key: "welcome", tableName: "Login", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Continuar
      static let `continue` = Rswift.StringResource(key: "continue", tableName: "Login", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Digite o seu e-mail para continuar
      static let digit_your_email_to_continue = Rswift.StringResource(key: "digit_your_email_to_continue", tableName: "Login", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: E-mail inválido, insira um e-mail valido para continuar
      static let invalid_email = Rswift.StringResource(key: "invalid_email", tableName: "Login", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: Bem vindo!
      static func welcome(_: Void = ()) -> String {
        return NSLocalizedString("welcome", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Continuar
      static func `continue`(_: Void = ()) -> String {
        return NSLocalizedString("continue", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Digite o seu e-mail para continuar
      static func digit_your_email_to_continue(_: Void = ()) -> String {
        return NSLocalizedString("digit_your_email_to_continue", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: E-mail inválido, insira um e-mail valido para continuar
      static func invalid_email(_: Void = ()) -> String {
        return NSLocalizedString("invalid_email", tableName: "Login", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = LoginViewController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
